apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaRzl5WlcxcE5EWTFPRHBuYUhCZk1FMDFhakZTY1V0RFIxSmhiM1UxT1dGMGFEWjZWM0JJZVZkR2JrcHBNRE00YUhsNSIKICAgIH0KICB9Cn0NCg==
type: kubernetes.io/dockerconfigjson
