apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaRzl5WlcxcE5EWTFPRHBuYUhCZmJHeG5jamd5TlhsMmNHUjZkbXQ0Ym5OMGVHVXpiM0ozIgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
